language: android

android:
  components:
    - platform-tools
    - build-tools-27.1.1
    - build-tools-27.0.3
    - android-27

before_install:
  - yes | sdkmanager "platforms;android-27"

checkout:
  post:
    - cp local.properties.ci local.properties