language: android
jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-27.1.1
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_install:
  - yes | sdkmanager "platforms;android-27"

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'