language: android

android:
  components:
    - platform-tools
    - build-tools-25.0.2
    - android-25

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'